at1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('eduprod/', include(('eduprod.urls', 'eduprod'), namespace='eduprod')),
    path('accounts/login/', include('users.urls')),
]

eduprod/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('submit-answer/', views.submit_answer, name='submit_answer'),
      path('questions/', views.display_questions, name='display_questions'),
]

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

eduprod/models.py
from django.db import models
from django.db import models

class ContinentQuestions(models.Model):
    CONTINENT_CHOICES = [
        ('Africa', 'Africa'),
        ('Asia', 'Asia'),
        ('Europe', 'Europe'),
        ('North America', 'North America'),
        ('South America', 'South America'),
        ('Oceania', 'Oceania'),
    ]

    question_text = models.CharField(max_length=200)
    answer_text = models.CharField(max_length=200)
    continent = models.CharField(max_length=50, choices=CONTINENT_CHOICES)

    def __str__(self):
        return f"{self.question_text} - {self.continent}"
    pass

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    answer_text = models.TextField()
    category = models.CharField(max_length=50, default='Europe')

    def __str__(self):
        return self.question_text

users/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=100)
    continent = models.CharField(max_length=50)

    def __str__(self):
        return self.name

eduprod/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'option1', 'option2', 'option3', 'option4', 'correct_option', 'image']

eduprod/views.py
from django.core import serializers
from django.shortcuts import render
from .models import Question
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from .models import ContinentQuestions
from django.shortcuts import render
from .models import Question

@login_required
def index(request):
    # Randomly select two questions
    questions = Question.objects.order_by('?')[:3]
    
    # Serialize the questions to JSON
    questions_json = serializers.serialize('json', questions)

    # Extracting categories from the Question model (assuming you have defined a category field)
    categories = Question.objects.values_list('category', flat=True).distinct()

    return render(request, 'eduprod/index.html', {
        'questions_json': questions_json,
        'categories': categories
    })

def submit_answer(request):
    if request.method == 'POST':
        user_answer = request.POST.get('answer')
        # Process the user's answer here
        return HttpResponse(f'Your answer: {user_answer}')
    else:
        return HttpResponse('Method not allowed')


def display_questions(request):
    questions = Question.objects.all()
    return render(request, 'africa/questions.html', {'questions': questions})

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render
from .models import Country

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            messages.success(request, "Invalid Credentials.")
            return render(request, "users/login.html")
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    messages.success(request, "Successfully logged out.")
    return redirect(reverse('users:login'))

def countries_by_continent(request, continent_name):
    countries = Country.objects.filter(continent=continent_name)
    return render(request, 'countries.html', {'continent': continent_name, 'countries': countries})

users/templates/users/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Q&A</title>
    <link href="{% static 'users/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="header">
        <div class="logo">
            <img src="{% static 'users/logo.gif' %}" alt="Logo">
        </div>
        <div class="user-info">
            <span>{{ user.username }}</span>
            <form action="{% url 'users:logout' %}" method="post" style="margin: o; margin-left: 25px;">
                {% csrf_token %}
                <button type="submit">Log out</button>
            </form>
        </div>
    </div>   
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}
{% block body %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Login">
</form>
{% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}
{% block body %}
    <h1 
    <span style="color: blue;">Flags</span>
    <span style="color: green;">Of</span>
    <span style="color: green;">The</span>
    <span style="color: blue;">World</span>
    </h1>
    <p>Username: {{ request.user.username }}</p>
    <a href="{% url 'eduprod:index' %}">Begin Guess
    </a>
{% endblock %}